// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbiQCBOweyKH6PvZ8N-lrol5i_4wRWfOY',
    appId: '1:639701934535:web:03d1e958d2e2394503f9e2',
    messagingSenderId: '639701934535',
    projectId: 'apiplayground-2f3be',
    authDomain: 'apiplayground-2f3be.firebaseapp.com',
    storageBucket: 'apiplayground-2f3be.appspot.com',
    measurementId: 'G-B8N3NP9EJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZS541wjXAmmSbOsPAJ5xEqkx3PIlM-Uk',
    appId: '1:639701934535:android:875569431e045dc603f9e2',
    messagingSenderId: '639701934535',
    projectId: 'apiplayground-2f3be',
    storageBucket: 'apiplayground-2f3be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAog41t_Evwvb7E1LdSAxioA-zgeLFwQHo',
    appId: '1:639701934535:ios:180acd88a977011e03f9e2',
    messagingSenderId: '639701934535',
    projectId: 'apiplayground-2f3be',
    storageBucket: 'apiplayground-2f3be.appspot.com',
    iosBundleId: 'com.example.apiplayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAog41t_Evwvb7E1LdSAxioA-zgeLFwQHo',
    appId: '1:639701934535:ios:705a86e4c9bedc5f03f9e2',
    messagingSenderId: '639701934535',
    projectId: 'apiplayground-2f3be',
    storageBucket: 'apiplayground-2f3be.appspot.com',
    iosBundleId: 'com.example.apiplayground.RunnerTests',
  );
}
